MvcOnlineTicariOtomasyon/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        // GET: Satis
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.SatisHarekets.ToList();
            return View(degerler);
        }
        
        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunId.ToString()
                                           }).ToList();

            List<SelectListItem> deger2 = (from x in c.Caris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyad,
                                               Value = x.CariId.ToString()
                                           }).ToList();

            List<SelectListItem> deger3 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelId.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            return View();
        }

        [HttpPost]
        public ActionResult YeniSatis(SatisHareket s)
        {
            s.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            c.SatisHarekets.Add(s);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunId.ToString()
                                           }).ToList();

            List<SelectListItem> deger2 = (from x in c.Caris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyad,
                                               Value = x.CariId.ToString()
                                           }).ToList();

            List<SelectListItem> deger3 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelId.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            var deger = c.SatisHarekets.Find(id);
            return View("SatisGetir", deger);
        }

        public ActionResult SatisGuncelle(SatisHareket p)
        {
            var deger = c.SatisHarekets.Find(p.SatisId);
            deger.Cariid = p.Cariid;
            deger.Adet = p.Adet;
            deger.Fiyat = p.Fiyat;
            deger.Personelid = p.Personelid;
            deger.Tarih = p.Tarih;
            deger.ToplamTutar = p.ToplamTutar;
            deger.Urunid = p.Urunid;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisDetay(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.SatisId == id).ToList();
            return View(degerler);
        }
      
    }
}

MvcOnlineTicariOtomasyon/Views/Satis/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout2.cshtml";
}
<body>
    <br />
    <div class="row">
        <div class="col-lg-12 col-sm-12">
            <div class="card">
                <div class="card-body table-responsive">
                    <h5 class="header-title">Satış Listesi</h5>
                    <table id="datatable" class="table table-bordered table-hover" style="margin-top:20px;">
                        <thead>
                            <tr class="table-active">
                                <th>ID</th>
                                <th>Ürün</th>
                                <th>Cari </th>
                                <th>Personel</th>
                                <th>Adet</th>
                                <th>Fiyat</th>
                                <th>Toplam Tutar</th>
                                <th>Tarih</th>
                                <th class="text-center">Güncelle</th>
                                <th class="text-center">Detaylar</th>
                            </tr>
                        </thead>
                        @foreach (var k in Model)
                        {
                            <tr>
                                <td>@k.SatisId</td>
                                <td>@k.Urun.UrunAd</td>
                                <td>@k.Cari.CariAd @k.Cari.CariSoyad</td>
                                <td>@k.Personel.PersonelAd @k.Personel.PersonelSoyad</td>
                                <td>@k.Adet</td>
                                <td>@k.Fiyat ₺</td>
                                <td>@k.ToplamTutar ₺</td>
                                <td>@k.Tarih</td>
                                <td width="15%" align="center"><a href="/Satis/SatisGetir/@k.SatisId" class="btn btn-warning">Güncelle</a></td>
                                <td width="15%" align="center"><a href="/Satis/SatisDetay/@k.SatisId" class="btn btn-success">Detaylar</a></td>
                            </tr>
                        }
                    </table>
                    <a href="/Satis/YeniSatis/" class="btn btn-primary">Yeni Satış Yap</a>
                </div>
            </div>
        </div>
    </div>
</body>

MvcOnlineTicariOtomasyon/Views/Satis/SatisDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{ ViewBag.Title = "SatisDetay";
   Layout = "~/Views/Shared/_AdminLayout2.cshtml"; 
}

<body>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="mt-0 header-title">Satış Detayı</h4>
                    <table class="table table-hover">
                        <tr class="table-active">
                            <th>Satış Id</th>
                            <th>Ürün</th>
                            <th>Marka</th>
                            <th>Cari</th>
                            <th>Personel</th>
                            <th>Adet</th>
                            <th>Fiyat</th>
                            <th>Toplam Fiyat</th>
                            <th>Tarih</th>
                        </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.SatisId</td>
                            <td>@item.Urun.UrunAd</td>
                            <td>@item.Urun.Marka</td>
                            <td>@item.Cari.CariAd @item.Cari.CariSoyad</td>
                            <td>@item.Personel.PersonelAd @item.Personel.PersonelSoyad</td>
                            <td>@item.Adet</td>
                            <td>@item.Fiyat ₺ </td>
                            <td>@item.ToplamTutar ₺</td>
                            <td>@item.Tarih</td>
                        </tr>
                    }
                    </table>
                    <button class="btn btn-warning">Yazdır</button>
                </div>
            </div><!--end card-body-->
        </div>
    </div>
</body>

MvcOnlineTicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/_AdminLayout2.cshtml";
}

<body>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="mt-0 header-title">Satış Bilgileri</h4>
                    @using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
                    {
                        @Html.HiddenFor(x => x.SatisId)

                        @Html.Label("Ürün")
                        @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
                        <br />
                        @Html.Label("Cari")
                        @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
                        <br />
                        @Html.Label("Personel")
                        @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
                        <br />
                        @Html.Label("Adet")
                        @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
                        <br />
                        @Html.Label("Fiyat")
                        @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
                        <br />
                        @Html.Label("Toplam Tutar")
                        @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
                        <br />
                        @Html.Label("Tarih")
                        @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
                        <br />
                        <button class="btn btn-warning">Güncelle</button>
                    }
                </div>
            </div><!--end card-body-->
        </div>
    </div>
</body>

MvcOnlineTicariOtomasyon/Views/Satis/YeniSatis.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{ ViewBag.Title = "YeniSatis";
   Layout = "~/Views/Shared/_AdminLayout2.cshtml"; 
}

<body>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="mt-0 header-title">Yeni Satış Sayfası</h4>
                    <form class="form-group" method="post">
                        @Html.Label("Ürün")
                        @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
                        <br />
                        @Html.Label("Cari")
                        @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
                        <br />
                        @Html.Label("Personel")
                        @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
                        <br />
                        @Html.Label("Adet")
                        @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
                        <br />
                        @Html.Label("Fiyat")
                        @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
                        <br />
                        @Html.Label("Toplam Tutar")
                        @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
                        <br />
                        <button class="btn btn-info">Satış Yap</button>
                    </form>
                </div>
            </div><!--end card-body-->
        </div>
    </div>

</body>