MvcOnlineTicariOtomasyon/Models/Siniflar/KargoTakip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class KargoTakip
    {
        [Key]
        public int KargoTakipId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(11)]
        public string TakipKodu { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(300)]
        public string Aciklama { get; set; }

        public DateTime TarihZaman  { get; set; }
    }
}

MvcOnlineTicariOtomasyon/Controllers/KargoController.cs
using MvcOnlineTicariOtomasyon.Models.Siniflar;
//using QRCoder;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class KargoController : Controller
    {
        // GET: Kargo
        Context c = new Context();
        public ActionResult Index()
        {
            var kargolar = c.KargoDetays.ToList();
            return View(kargolar);
        }

        [HttpGet]
        public ActionResult YeniKargo()
        {
            Random rnd = new Random();
            int sayi1, sayi2, sayi3, sayi4, sayi5;
            int harf, harf2, harf3, harf4;
            sayi1 = rnd.Next(1, 9);
            sayi2 = rnd.Next(0, 9);
            sayi3 = rnd.Next(0, 9);
            sayi4 = rnd.Next(1, 9);
            harf = rnd.Next(65, 91);
            sayi5 = rnd.Next(65, 91);
            harf2 = rnd.Next(65, 91);
            harf3 = rnd.Next(65, 91);
            harf4 = rnd.Next(65, 91);
            if (harf == harf2)
            {
                harf2 = rnd.Next(65, 91);
            }
            if (harf2 == harf3)
            {
                harf3 = rnd.Next(65, 91);
            }
            if (harf3 == harf4)
            {
                harf4 = rnd.Next(65, 91);
            }
            if (sayi1 == sayi2)
            {
                sayi2 = rnd.Next(1, 9);
            }
            if (sayi2 == sayi3)
            {
                sayi3 = rnd.Next(0, 9);
            }
            if (sayi3 == sayi4)
            {
                sayi4 = rnd.Next(1, 9);
            }
            if (sayi4 == sayi5)
            {
                sayi5 = rnd.Next(0, 9);
            }
            char karakter;
            char karakter2;
            char karakter3;
            char karakter4;
            karakter = Convert.ToChar(harf);
            karakter2 = Convert.ToChar(harf2);
            karakter3 = Convert.ToChar(harf3);
            karakter4 = Convert.ToChar(harf4);
            string kod = sayi1.ToString() + sayi2.ToString() + karakter + sayi3.ToString() + sayi4.ToString() + karakter2 + sayi4.ToString() + karakter3 + sayi5.ToString() + karakter4;
            ViewBag.takipKod = kod;
            return View();
        }

        [HttpPost]
        public ActionResult YeniKargo(KargoDetay d)
        {
            c.KargoDetays.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index", "Kargo");
        }

        public ActionResult KargoTakip(string id)
        {
            var degerler = c.KargoTakips.Where(x => x.TakipKodu == id).ToList();
           
            return View(degerler);
        }


        public ActionResult QR(int id)
        {
            var deger = c.KargoDetays.Find(id);
            ViewBag.dgr = deger.TakipKodu;
            return View();
        }

        //[HttpPost]
        //public ActionResult QR(string kod)
        //{
        //    using (MemoryStream ms = new MemoryStream())
        //    {
        //        QRCodeGenerator kodUret = new QRCodeGenerator();
        //        QRCodeGenerator.QRCode kareKod = kodUret.CreateQrCode(kod, QRCodeGenerator.ECCLevel.Q);
        //        using (Bitmap resim = kareKod.GetGraphic(10))
        //        {
        //            resim.Save(ms, ImageFormat.Png);
        //            ViewBag.karekodimage = "data:image/png;base64," + Convert.ToBase64String
        //                (ms.ToArray());
        //        }
        //    }
        //    return View();
        //}
    }
}

MvcOnlineTicariOtomasyon/Controllers/QRController.cs
//using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class QRController : Controller
    {
        // GET: QR
        public ActionResult Index()
        {
            return View();
        }

        //[HttpPost]
        //public ActionResult Index(string kod)
        //{
        //    using (MemoryStream ms = new MemoryStream())
        //    {
        //        QRCodeGenerator kodUret = new QRCodeGenerator();
        //        QRCodeGenerator.QRCode kareKod = kodUret.CreateQrCode(kod,QRCodeGenerator.ECCLevel.Q);
        //        using (Bitmap resim = kareKod.GetGraphic(10))
        //        {
        //            resim.Save(ms, ImageFormat.Png);
        //            ViewBag.karekodimage = "data:image/png;base64," + Convert.ToBase64String
        //                (ms.ToArray());
        //        }
        //    }
        //    return View();
        //}

    }
}

MvcOnlineTicariOtomasyon/Views/Kargo/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<KargoDetay>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout2.cshtml";
}

<body>
    <br />
    <div class="row">
        <div class="col-lg-12 col-sm-12">
            <div class="card">
                <div class="card-body table-responsive">
                    <h5 class="header-title">Kargo Listesi</h5>
                    <table id="datatable" class="table table-bordered table-hover" style="margin-top:20px;">
                        <thead>
                            <tr class="table-active">                                        
                                <th>Personel</th>
                                <th>Alıcı</th>
                                <th>Takip Kodu</th>
                                <th>Tarih</th>
                                <th class="text-center">Detaylar</th>
                                <th class="text-center">QR Kod</th>
                                          
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var k in Model)
                            {
                                <tr>                                           
                                    <td>@k.Personel</td>
                                    <td>@k.Alici</td>
                                    <td>@k.TakipKodu</td>
                                    <td>@k.Tarih</td>
                                    <td class="text-center"><a href="/Kargo/KargoTakip/@k.TakipKodu/" class="btn btn-warning">Detay</a></td>
                                    <td class="text-center"><a href="/Kargo/QR/@k.KargoDetayId/" class="btn btn-success">QR Kod</a></td>
                                              
                                </tr>
                            }
                        </tbody>
                    </table>
                    <a href="/Kargo/YeniKargo" class="btn btn-primary">Yeni Kargo Ekle</a>
                </div>
            </div>
        </div>
    </div>
</body>

MvcOnlineTicariOtomasyon/Views/Kargo/KargoTakip.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<KargoTakip>
@{
    ViewBag.Title = "KargoTakip";
    Layout = "~/Views/Shared/_AdminLayout2.cshtml";
}

<body>
    <div class="page-wrapper">
        <!-- Page Content-->
        <div class="page-content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-sm-12">
                        <div class="card">
                            <div class="card-body table-responsive">
                                <h5 class="header-title">Kargo Hareketleri</h5>
                                <table id="#" class="table table-bordered table-hover" style="margin-top:20px;">
                                    <thead>
                                        <tr class="table-active">
                                            <th>Açıklama</th>
                                            <th>Tarih</th>

                                        </tr>
                                    </thead>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Aciklama</td>
                                            <td>@item.TarihZaman</td>

                                        </tr>
                                    }
                                </table>                             
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

MvcOnlineTicariOtomasyon/Views/Kargo/QR.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout2.cshtml";
}

<br />

<div>
    @using (Html.BeginForm("Index", "QR", FormMethod.Post))
    {
        <input type="text" name="kod" value="@ViewBag.dgr" />
        <input type="submit" value="QR Oluştur" />
    }

    @if (ViewBag.kareKodImage != null)
    {
        <img src="@ViewBag.kareKodImage" alt="" style="width:400px" height="400px" />
    }
</div>

MvcOnlineTicariOtomasyon/Views/Kargo/YeniKargo.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.KargoDetay
@{
    ViewBag.Title = "YeniKargo";
   Layout = "~/Views/Shared/_AdminLayout2.cshtml"; 
}

<body>
    <br />
    <div class="card">
        <div class="card-body">
            <h4 class="mt-0 header-title">Kargo Bilgileri</h4>
            <form class="form-group" method="post">
                <div class="form-group">
                    @Html.Label("Takip Kodu")
                    <input type="text" value="@ViewBag.takipKod" class="form-control" readonly name="TakipKodu" />              
                    <br />
                    @Html.Label("Personel")
                    @Html.TextBoxFor(x => x.Personel, new { @class = "form-control", @placeholder = "Personel*" })             
                    <br />
                    @Html.Label("Alıcı")
                    @Html.TextBoxFor(x => x.Alici, new { @class = "form-control", @placeholder = "Alıcı*" })           
                    <br />
                    @Html.Label("Tarih")
                    <input type="date" class="form-control" name="Tarih" />
                    <br />
                    @Html.Label("Açıklama")
                    @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control", @placeholder = "Açıklama*" })
                </div>
                <button class="btn btn-info">Kaydet</button>

            </form>
        </div><!--end card-body-->
    </div><!--end card-->
</body>